#!/usr/bin/env python3
"""
Pairwise EPAC tropical-cyclone comparison.

Models
------
GraphCast
AIFS2
Pangu3

Tracker
-------
WuDuan

The script compares models at exact common valid times using
full-coverage verification points already generated by AIWeather.

Products
--------
1. Pairwise common-point CSV
2. Pairwise summary CSV
3. Pairwise coverage CSV
4. Pairwise track-error figure
5. Genevieve AIFS2-vs-Pangu3 diagnostic figure

The existing strict three-model benchmark is not modified.
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt

from aiweather.plotting.model_style import (
    model_color,
    model_label,
    model_marker,
)
import numpy as np
import pandas as pd


# ============================================================
# Configuration
# ============================================================

BASE = Path(
    "results/verification/batch"
)

MODEL_PATHS = {
    "graphcast": (
        BASE
        / "graphcast_epac_4storm"
        / "batch_points.csv"
    ),
    "aifs2": (
        BASE
        / "aifs2_epac_4storm"
        / "batch_points.csv"
    ),
    "pangu3": (
        BASE
        / "pangu3_epac_4storm"
        / "batch_points.csv"
    ),
}

OUTPUT_DIR = Path(
    "results/verification/comparison/"
    "epac_pairwise_4storm"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

TRACKER = "wuduan"
COVERAGE = "full"

MINIMUM_COMMON_POINTS = 6

STORMS = [
    (
        "elida_20260714T120000",
        "Elida",
    ),
    (
        "fausto_20260719T000000",
        "Fausto",
    ),
    (
        "genevieve_20260724T000000",
        "Genevieve",
    ),
    (
        "hernan_20260811T000000",
        "Hernan",
    ),
]

PAIRS = [
    (
        "graphcast",
        "aifs2",
    ),
    (
        "graphcast",
        "pangu3",
    ),
    (
        "aifs2",
        "pangu3",
    ),
]

LEAD_TICKS = [
    0,
    24,
    48,
    72,
    96,
    120,
    144,
    168,
    192,
    216,
    240,
]


# ============================================================
# Helpers
# ============================================================

def rmse(values):
    """
    Root-mean-square error.
    """

    values = np.asarray(
        values,
        dtype=float,
    )

    return float(
        np.sqrt(
            np.mean(
                values ** 2
            )
        )
    )


def to_lon180(values):
    """
    Convert longitude to -180 to 180.
    """

    values = np.asarray(
        values,
        dtype=float,
    )

    return (
        (values + 180.0)
        % 360.0
        - 180.0
    )


def load_model_points(
    path: Path,
) -> pd.DataFrame:
    """
    Read one batch point table and keep full WuDuan coverage.
    """

    df = pd.read_csv(
        path,
        parse_dates=[
            "initialization_time",
            "valid_time",
        ],
    )

    df = df[
        (
            df["tracker"]
            == TRACKER
        )
        & (
            df["coverage"]
            == COVERAGE
        )
    ].copy()

    return df


def build_pair(
    left: pd.DataFrame,
    right: pd.DataFrame,
    model_left: str,
    model_right: str,
    case_id: str,
    storm_name: str,
) -> pd.DataFrame:
    """
    Build one exact-valid-time pairwise table.
    """

    columns = [
        "case_id",
        "sid",
        "valid_time",
        "lead_time_hours",
        "forecast_latitude",
        "forecast_longitude",
        "observed_latitude",
        "observed_longitude",
        "track_error_km",
        "forecast_pressure_pa",
        "observed_pressure_pa",
        "pressure_error_pa",
        "forecast_wind_ms",
        "observed_wind_ms",
        "wind_error_ms",
    ]

    a = left[
        left[
            "case_id"
        ]
        == case_id
    ][
        columns
    ].copy()

    b = right[
        right[
            "case_id"
        ]
        == case_id
    ][
        columns
    ].copy()

    paired = a.merge(
        b,
        on=[
            "case_id",
            "sid",
            "valid_time",
        ],
        how="inner",
        suffixes=(
            f"_{model_left}",
            f"_{model_right}",
        ),
    )

    if paired.empty:
        return paired

    lead_left = (
        paired[
            f"lead_time_hours_{model_left}"
        ]
        .to_numpy()
    )

    lead_right = (
        paired[
            f"lead_time_hours_{model_right}"
        ]
        .to_numpy()
    )

    if not np.array_equal(
        lead_left,
        lead_right,
    ):
        raise RuntimeError(
            f"Lead times do not match for "
            f"{storm_name}: "
            f"{model_left} vs {model_right}"
        )

    paired[
        "lead_time_hours"
    ] = paired[
        f"lead_time_hours_{model_left}"
    ]

    paired[
        "storm"
    ] = storm_name

    paired[
        "model_1"
    ] = model_left

    paired[
        "model_2"
    ] = model_right

    paired[
        "pair"
    ] = (
        f"{model_left}_vs_{model_right}"
    )

    paired[
        "track_error_difference_km"
    ] = (
        paired[
            f"track_error_km_{model_left}"
        ]
        - paired[
            f"track_error_km_{model_right}"
        ]
    )

    paired[
        "best_model"
    ] = np.where(
        paired[
            f"track_error_km_{model_left}"
        ]
        < paired[
            f"track_error_km_{model_right}"
        ],
        model_left,
        np.where(
            paired[
                f"track_error_km_{model_right}"
            ]
            < paired[
                f"track_error_km_{model_left}"
            ],
            model_right,
            "equal",
        ),
    )

    paired[
        "observed_latitude"
    ] = paired[
        f"observed_latitude_{model_left}"
    ]

    paired[
        "observed_longitude"
    ] = paired[
        f"observed_longitude_{model_left}"
    ]

    paired[
        "observed_longitude_plot"
    ] = to_lon180(
        paired[
            "observed_longitude"
        ]
    )

    for model in [
        model_left,
        model_right,
    ]:

        paired[
            f"forecast_longitude_plot_{model}"
        ] = to_lon180(
            paired[
                f"forecast_longitude_{model}"
            ]
        )

    return paired


def summarize_pair(
    paired: pd.DataFrame,
    model_left: str,
    model_right: str,
    case_id: str,
    storm_name: str,
):
    """
    Build numerical summary for one model pair and storm.
    """

    if paired.empty:
        return None

    row = {
        "case_id":
            case_id,

        "storm":
            storm_name,

        "pair":
            (
                f"{model_left}_vs_"
                f"{model_right}"
            ),

        "model_1":
            model_left,

        "model_2":
            model_right,

        "common_points":
            len(
                paired
            ),

        "first_lead_time_h":
            int(
                paired[
                    "lead_time_hours"
                ].min()
            ),

        "last_lead_time_h":
            int(
                paired[
                    "lead_time_hours"
                ].max()
            ),

        "eligible_for_comparison":
            (
                len(
                    paired
                )
                >= MINIMUM_COMMON_POINTS
            ),
    }

    for model in [
        model_left,
        model_right,
    ]:

        track = paired[
            f"track_error_km_{model}"
        ]

        pressure_hpa = (
            paired[
                f"pressure_error_pa_{model}"
            ]
            / 100.0
        )

        wind = paired[
            f"wind_error_ms_{model}"
        ]

        row[
            f"{model}_track_mean_km"
        ] = float(
            track.mean()
        )

        row[
            f"{model}_track_rmse_km"
        ] = rmse(
            track
        )

        row[
            f"{model}_track_median_km"
        ] = float(
            track.median()
        )

        row[
            f"{model}_track_maximum_km"
        ] = float(
            track.max()
        )

        row[
            f"{model}_track_best_points"
        ] = int(
            (
                paired[
                    "best_model"
                ]
                == model
            ).sum()
        )

        row[
            f"{model}_track_best_fraction"
        ] = float(
            (
                paired[
                    "best_model"
                ]
                == model
            ).mean()
        )

        row[
            f"{model}_pressure_bias_hpa"
        ] = float(
            pressure_hpa.mean()
        )

        row[
            f"{model}_pressure_mae_hpa"
        ] = float(
            pressure_hpa.abs().mean()
        )

        row[
            f"{model}_pressure_rmse_hpa"
        ] = rmse(
            pressure_hpa
        )

        row[
            f"{model}_wind_bias_ms"
        ] = float(
            wind.mean()
        )

        row[
            f"{model}_wind_mae_ms"
        ] = float(
            wind.abs().mean()
        )

        row[
            f"{model}_wind_rmse_ms"
        ] = rmse(
            wind
        )

    row[
        "mean_track_difference_km"
    ] = float(
        paired[
            "track_error_difference_km"
        ].mean()
    )

    return row


def save_figure(
    fig,
    stem: str,
):
    """
    Save PNG and PDF.
    """

    png = (
        OUTPUT_DIR
        / f"{stem}.png"
    )

    pdf = (
        OUTPUT_DIR
        / f"{stem}.pdf"
    )

    fig.savefig(
        png,
        dpi=200,
        bbox_inches="tight",
    )

    fig.savefig(
        pdf,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )

    return png, pdf


# ============================================================
# Load model tables
# ============================================================

data = {}

for model, path in MODEL_PATHS.items():

    data[
        model
    ] = load_model_points(
        path
    )

    print(
        f"{model_label(model):<10s}: "
        f"{len(data[model])} "
        "full WuDuan points"
    )


# ============================================================
# Build all pairwise common-time tables
# ============================================================

pair_tables = []
summary_rows = []
coverage_rows = []

for (
    case_id,
    storm_name,
) in STORMS:

    for (
        model_left,
        model_right,
    ) in PAIRS:

        paired = build_pair(
            data[
                model_left
            ],
            data[
                model_right
            ],
            model_left,
            model_right,
            case_id,
            storm_name,
        )

        coverage_rows.append(
            {
                "case_id":
                    case_id,

                "storm":
                    storm_name,

                "pair":
                    (
                        f"{model_left}_vs_"
                        f"{model_right}"
                    ),

                "model_1":
                    model_left,

                "model_2":
                    model_right,

                "common_points":
                    len(
                        paired
                    ),

                "eligible_for_comparison":
                    (
                        len(
                            paired
                        )
                        >= MINIMUM_COMMON_POINTS
                    ),
            }
        )

        if paired.empty:
            continue

        pair_tables.append(
            paired
        )

        summary = summarize_pair(
            paired,
            model_left,
            model_right,
            case_id,
            storm_name,
        )

        summary_rows.append(
            summary
        )


if pair_tables:

    common = pd.concat(
        pair_tables,
        ignore_index=True,
    )

else:

    common = pd.DataFrame()


summary = pd.DataFrame(
    summary_rows
)

coverage = pd.DataFrame(
    coverage_rows
)


# ============================================================
# Save CSV products
# ============================================================

common_path = (
    OUTPUT_DIR
    / "epac_pairwise_common_points.csv"
)

summary_path = (
    OUTPUT_DIR
    / "epac_pairwise_summary.csv"
)

coverage_path = (
    OUTPUT_DIR
    / "epac_pairwise_coverage.csv"
)

common.to_csv(
    common_path,
    index=False,
)

summary.to_csv(
    summary_path,
    index=False,
)

coverage.to_csv(
    coverage_path,
    index=False,
)


# ============================================================
# Figure 1
# Pairwise track error by storm
# ============================================================

fig, axes = plt.subplots(
    4,
    3,
    figsize=(
        17,
        16,
    ),
    sharex=True,
)

for row_index, (
    case_id,
    storm_name,
) in enumerate(
    STORMS
):

    for col_index, (
        model_left,
        model_right,
    ) in enumerate(
        PAIRS
    ):

        ax = axes[
            row_index,
            col_index,
        ]

        subset = common[
            (
                common[
                    "case_id"
                ]
                == case_id
            )
            & (
                common[
                    "pair"
                ]
                == (
                    f"{model_left}_vs_"
                    f"{model_right}"
                )
            )
        ].sort_values(
            "lead_time_hours"
        )

        if subset.empty:

            ax.text(
                0.5,
                0.5,
                "No exact common times",
                transform=ax.transAxes,
                ha="center",
                va="center",
            )

        else:

            for model in [
                model_left,
                model_right,
            ]:

                ax.plot(
                    subset[
                        "lead_time_hours"
                    ],
                    subset[
                        f"track_error_km_{model}"
                    ],
                    marker=model_marker(model),
                    markersize=4,
                    linewidth=1.8,
                    color=model_color(model),
                    label=model_label(model),
                )

        if row_index == 0:

            ax.set_title(
                (
                    f"{model_label(model_left)} "
                    f"vs "
                    f"{model_label(model_right)}"
                ),
                fontweight="bold",
            )

        if col_index == 0:

            ax.set_ylabel(
                f"{storm_name}\n"
                "Track error (km)"
            )

        if row_index == (
            len(
                STORMS
            )
            - 1
        ):

            ax.set_xlabel(
                "Forecast lead time (h)"
            )

        ax.set_xlim(
            0,
            240,
        )

        ax.set_xticks(
            LEAD_TICKS
        )

        ax.tick_params(
            axis="x",
            rotation=45,
        )

        ax.grid(
            True,
            alpha=0.3,
        )

        if (
            row_index == 0
            and col_index == 0
        ):

            ax.legend(
                fontsize=8
            )


fig.suptitle(
    "EPAC Pairwise Tropical Cyclone Track Error\n"
    "WuDuan Tracker — Exact Common Valid Times",
    fontsize=15,
    fontweight="bold",
)

fig.tight_layout(
    rect=[
        0,
        0,
        1,
        0.95,
    ]
)

pairwise_track_png, pairwise_track_pdf = (
    save_figure(
        fig,
        "epac_pairwise_track_error",
    )
)


# ============================================================
# Figure 2
# Genevieve AIFS2 vs Pangu3 diagnostic
# ============================================================

genevieve = common[
    (
        common[
            "case_id"
        ]
        == "genevieve_20260724T000000"
    )
    & (
        common[
            "pair"
        ]
        == "aifs2_vs_pangu3"
    )
].sort_values(
    "lead_time_hours"
)

genevieve_png = None
genevieve_pdf = None

if not genevieve.empty:

    fig, axes = plt.subplots(
        2,
        2,
        figsize=(
            14,
            10,
        ),
    )

    # --------------------------------------------------------
    # Track
    # --------------------------------------------------------

    ax = axes[
        0,
        0,
    ]

    ax.plot(
        genevieve[
            "observed_longitude_plot"
        ],
        genevieve[
            "observed_latitude"
        ],
        marker="o",
        linewidth=2.2,
        label="IBTrACS",
    )

    for model in [
        "aifs2",
        "pangu3",
    ]:

        ax.plot(
            genevieve[
                f"forecast_longitude_plot_{model}"
            ],
            genevieve[
                f"forecast_latitude_{model}"
            ],
            marker=model_marker(model),
            linewidth=2,
            color=model_color(model),
            label=model_label(model),
        )

    ax.set_xlabel(
        "Longitude (°)"
    )

    ax.set_ylabel(
        "Latitude (°)"
    )

    ax.set_title(
        "Track"
    )

    ax.grid(
        True,
        alpha=0.3,
    )

    ax.legend()

    # --------------------------------------------------------
    # Track error
    # --------------------------------------------------------

    ax = axes[
        0,
        1,
    ]

    for model in [
        "aifs2",
        "pangu3",
    ]:

        ax.plot(
            genevieve[
                "lead_time_hours"
            ],
            genevieve[
                f"track_error_km_{model}"
            ],
            marker=model_marker(model),
            linewidth=2,
            color=model_color(model),
            label=model_label(model),
        )

    ax.set_xlabel(
        "Forecast lead time (h)"
    )

    ax.set_ylabel(
        "Track error (km)"
    )

    ax.set_title(
        "Track error"
    )

    ax.grid(
        True,
        alpha=0.3,
    )

    ax.legend()

    # --------------------------------------------------------
    # Pressure error
    # --------------------------------------------------------

    ax = axes[
        1,
        0,
    ]

    for model in [
        "aifs2",
        "pangu3",
    ]:

        ax.plot(
            genevieve[
                "lead_time_hours"
            ],
            (
                genevieve[
                    f"pressure_error_pa_{model}"
                ]
                / 100.0
            ),
            marker=model_marker(model),
            linewidth=2,
            color=model_color(model),
            label=model_label(model),
        )

    ax.axhline(
        0.0,
        linewidth=1.0,
    )

    ax.set_xlabel(
        "Forecast lead time (h)"
    )

    ax.set_ylabel(
        "Pressure error (hPa)"
    )

    ax.set_title(
        "Central-pressure error"
    )

    ax.grid(
        True,
        alpha=0.3,
    )

    ax.legend()

    # --------------------------------------------------------
    # Wind error
    # --------------------------------------------------------

    ax = axes[
        1,
        1,
    ]

    for model in [
        "aifs2",
        "pangu3",
    ]:

        ax.plot(
            genevieve[
                "lead_time_hours"
            ],
            genevieve[
                f"wind_error_ms_{model}"
            ],
            marker=model_marker(model),
            linewidth=2,
            color=model_color(model),
            label=model_label(model),
        )

    ax.axhline(
        0.0,
        linewidth=1.0,
    )

    ax.set_xlabel(
        "Forecast lead time (h)"
    )

    ax.set_ylabel(
        "Wind error (m/s)"
    )

    ax.set_title(
        "Maximum-wind error"
    )

    ax.grid(
        True,
        alpha=0.3,
    )

    ax.legend()

    fig.suptitle(
        "Genevieve — AIFS2 vs Pangu3\n"
        "WuDuan Exact Common Valid Times",
        fontsize=15,
        fontweight="bold",
    )

    fig.tight_layout(
        rect=[
            0,
            0,
            1,
            0.94,
        ]
    )

    (
        genevieve_png,
        genevieve_pdf,
    ) = save_figure(
        fig,
        "genevieve_aifs2_vs_pangu3",
    )


# ============================================================
# Console output
# ============================================================

print()
print("=" * 100)
print(
    "EPAC PAIRWISE TROPICAL-CYCLONE COMPARISON"
)
print("=" * 100)

print()
print(
    "Tracker                  :",
    TRACKER,
)

print(
    "Coverage                 :",
    COVERAGE,
)

print(
    "Minimum common points    :",
    MINIMUM_COMMON_POINTS,
)

print()

display_columns = [
    "storm",
    "pair",
    "common_points",
    "first_lead_time_h",
    "last_lead_time_h",
    "eligible_for_comparison",
]

print(
    summary[
        display_columns
    ].to_string(
        index=False,
    )
)


# ============================================================
# Genevieve numerical summary
# ============================================================

genevieve_summary = summary[
    (
        summary[
            "case_id"
        ]
        == "genevieve_20260724T000000"
    )
    & (
        summary[
            "pair"
        ]
        == "aifs2_vs_pangu3"
    )
]

if not genevieve_summary.empty:

    row = genevieve_summary.iloc[
        0
    ]

    print()
    print("=" * 100)
    print(
        "GENEVIEVE — AIFS2 VS PANGU3"
    )
    print("=" * 100)
    print()

    print(
        "Exact common points:",
        int(
            row[
                "common_points"
            ]
        ),
    )

    print(
        "Lead range:",
        (
            f"{int(row['first_lead_time_h'])}"
            "-"
            f"{int(row['last_lead_time_h'])} h"
        ),
    )

    print()

    for model in [
        "aifs2",
        "pangu3",
    ]:

        print(
            model_label(model)
        )

        print(
            "  Track mean : "
            f"{row[f'{model}_track_mean_km']:.2f} km"
        )

        print(
            "  Track RMSE : "
            f"{row[f'{model}_track_rmse_km']:.2f} km"
        )

        print(
            "  Track wins : "
            f"{int(row[f'{model}_track_best_points'])}"
        )

        print(
            "  P bias     : "
            f"{row[f'{model}_pressure_bias_hpa']:.2f} hPa"
        )

        print(
            "  P MAE      : "
            f"{row[f'{model}_pressure_mae_hpa']:.2f} hPa"
        )

        print(
            "  P RMSE     : "
            f"{row[f'{model}_pressure_rmse_hpa']:.2f} hPa"
        )

        print(
            "  W bias     : "
            f"{row[f'{model}_wind_bias_ms']:.2f} m/s"
        )

        print(
            "  W MAE      : "
            f"{row[f'{model}_wind_mae_ms']:.2f} m/s"
        )

        print(
            "  W RMSE     : "
            f"{row[f'{model}_wind_rmse_ms']:.2f} m/s"
        )

        print()


# ============================================================
# Output paths
# ============================================================

print("=" * 100)
print("OUTPUT PRODUCTS")
print("=" * 100)
print()

print(
    "Common points:",
    common_path,
)

print(
    "Summary:",
    summary_path,
)

print(
    "Coverage:",
    coverage_path,
)

print(
    "Pairwise track errors:",
    pairwise_track_png,
)

if genevieve_png is not None:

    print(
        "Genevieve diagnostic:",
        genevieve_png,
    )